const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');let pw;
for(const f of fs.readdirSync(path.join(process.env.LOCALAPPDATA,'ms-playwright/.links'))){try{pw=require(fs.readFileSync(path.join(process.env.LOCALAPPDATA,'ms-playwright/.links',f),'utf8').trim());break;}catch{}}
const base=path.resolve(__dirname,'..'),canonical=path.resolve(base,'../..'),publicRoot=path.join(base,'source-public');
const target=process.env.AW_VISUAL_BASE||'https://neomundi.cloud',label=process.env.AW_COMPARE_LABEL||'canonical-live';assert(['https://neomundi.cloud','http://127.0.0.1:9402'].includes(target));assert(/^[a-z0-9-]+$/.test(label));
const pages=(process.env.AW_COMPARE_PAGES||'home,widgets').split(','),names={home:'index',widgets:'widgets','how-it-works':'how-it-works','us-station':'us-station',today:'today',stations:'stations','for-media':'for-media',about:'about',contact:'contact','daily-brief':'daily-brief'};pages.forEach(k=>assert(names[k]));
const out=path.join(base,'test-results',label);fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{const u=decodeURIComponent(new URL(req.url,'http://localhost').pathname);let file;if(u.startsWith('/redesign/')){file=path.resolve(canonical,u.slice(10));if(!file.startsWith(canonical+path.sep)||file.includes('wordpress-staging-worktree')){res.writeHead(404);return res.end();}}else{file=path.resolve(publicRoot,'.'+u);if(!file.startsWith(publicRoot+path.sep)){res.writeHead(404);return res.end();}}if(!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);return res.end();}let bytes=fs.readFileSync(file);if(file.endsWith('.html'))bytes=Buffer.from(bytes.toString('utf8').replaceAll('https://weather.controltowerai.io/','http://127.0.0.1:9474/'));res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.css':'text/css','.js':'text/javascript','.json':'application/json','.png':'image/png','.ico':'image/x-icon'})[path.extname(file)]||'application/octet-stream');res.end(bytes);});
(async()=>{await new Promise(r=>server.listen(9474,'127.0.0.1',r));const b=await pw.chromium.launch({headless:true}),c=await b.newContext(),p=await c.newPage(),report={pairs:[],network:[],errors:[]};let current='';await c.addCookies([{name:'playground_auto_login_already_happened',value:'1',url:'http://127.0.0.1:9402'}]);await c.route('**/*',r=>['controltowerai.io','www.controltowerai.io','weather.controltowerai.io'].includes(new URL(r.request().url()).hostname)?r.abort():r.continue());p.on('pageerror',e=>report.errors.push({page:current,message:e.message}));c.on('response',r=>{if(r.status()>=400)report.network.push({page:current,status:r.status(),url:r.url()});});
const save=()=>fs.writeFileSync(path.join(out,'comparison.json'),JSON.stringify(report,null,2));
try{for(const key of pages)for(const width of [1440,390]){const pair={page:key,width};await p.setViewportSize({width,height:1000});for(const kind of ['source','wordpress']){current=key+'-'+width+'-'+kind;const url=kind==='source'?'http://127.0.0.1:9474/redesign/'+names[key]+'.html':target+'/'+(key==='home'?'':key+'/');const r=await p.goto(url,{waitUntil:'domcontentloaded',timeout:60000});await p.evaluate(()=>document.fonts.ready);await p.waitForTimeout(key==='us-station'?4500:1800);
const metrics=await p.evaluate(()=>{const styles={};for(const selector of ['.site-header','.station-topbar','h1','.hero','main','section','footer','.format-grid','.preview-wrap','.us-observatory'])styles[selector]=[...document.querySelectorAll(selector)].map(e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return {x:r.x,y:r.y,width:r.width,height:r.height,font:s.font,color:s.color,background:s.backgroundImage,backgroundColor:s.backgroundColor};});return {themeVersionLoaded:[...document.styleSheets].some(s=>s.href&&s.href.includes('/ai-weather/style.css?ver=0.2.0')),styles,raw:document.querySelectorAll('body>.wp-block-heading,body>.wp-block-button,body>p').length,editorHints:/Lien â€” hero|Textes, traductions et liens Ã©ditables|@@FIELD:/.test(document.body.innerText),overflow:document.documentElement.scrollWidth>innerWidth+1,h1:document.querySelector('h1')?.textContent};});
pair[kind]={status:r.status(),renderer:r.headers()['x-ai-weather-renderer'],...metrics};await p.screenshot({path:path.join(out,current+'.png'),fullPage:true});assert.equal(r.status(),200);assert.equal(metrics.raw,0);assert(!metrics.editorHints);if(kind==='wordpress'){assert(r.headers()['x-ai-weather-renderer']==='canonical-0.2.0'||metrics.themeVersionLoaded);assert(!metrics.overflow);}}
pair.differences=[];for(const [selector,items] of Object.entries(pair.source.styles))items.forEach((a,i)=>{const b=pair.wordpress.styles[selector]?.[i];if(!b){pair.differences.push(selector+' missing');return;}for(const field of Object.keys(a)){if(typeof a[field]==='number'?Math.abs(a[field]-b[field])>1:a[field]!==b[field])pair.differences.push({selector,index:i,field,source:a[field],wordpress:b[field]});}});report.pairs.push(pair);save();console.log(key,width,'differences='+pair.differences.length);}
}finally{save();await b.close();server.close();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
