const fs=require('fs'),path=require('path'),assert=require('assert/strict');let pw;for(const f of fs.readdirSync(path.join(process.env.LOCALAPPDATA,'ms-playwright/.links'))){try{pw=require(fs.readFileSync(path.join(process.env.LOCALAPPDATA,'ms-playwright/.links',f),'utf8').trim());break;}catch{}}
const out=path.resolve(__dirname,'../test-results/media-after');fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await pw.chromium.launch({headless:true}),c=await b.newContext(),p=await c.newPage(),report={redirects:[],internal:[],external:[],sitemaps:[]},links=new Set();await c.route('**/*',r=>['controltowerai.io','www.controltowerai.io','weather.controltowerai.io'].includes(new URL(r.request().url()).hostname)?r.abort():r.continue());try{
for(const old of ['/for-media/','/for-media','/for-media.html','/fr/for-media/','/?page_id=137']){const r=await c.request.get('https://neomundi.cloud'+old,{maxRedirects:0});report.redirects.push({path:old,status:r.status(),location:r.headers().location});assert.equal(r.status(),301);assert.equal(r.headers().location,'https://neomundi.cloud/how-it-works/');}
for(const slug of ['','how-it-works/','widgets/','today/','stations/','daily-brief/','about/','contact/','us-station/','quiz/']){await p.goto('https://neomundi.cloud/'+slug,{waitUntil:'domcontentloaded'});const result=await p.evaluate(()=>({links:[...document.querySelectorAll('a[href]')].map(a=>a.href),columns:[...document.querySelectorAll('.footer-col')].filter(e=>e.querySelector('h4')?.textContent==='Company').map(e=>[...e.querySelectorAll('a')].map(a=>[a.textContent,a.href,a.rel,a.target]))}));for(const col of result.columns){assert.deepEqual(col.map(a=>a.slice(0,2)),[['NeoMundi.org','https://neomundi.org/'],['NeoMundi.io','https://neomundi.io/'],['ControlTower API','https://controltower.neomundi.io/']]);assert(col.every(a=>a[2].includes('noopener')&&a[2].includes('noreferrer')&&a[3]==='_blank'));}for(const url of result.links){const u=new URL(url);if(u.hostname==='neomundi.cloud'){assert(!u.pathname.includes('for-media'));u.hash='';links.add(u.href);}}}
for(const url of links){const r=await c.request.get(url,{maxRedirects:0});report.internal.push({url,status:r.status()});assert(r.status()<400,'Broken internal link: '+url);}
for(const original of ['https://neomundi.org','https://neomundi.io','https://controltower.neomundi.io']){let url=original,chain=[];try{for(let i=0;i<6;i++){if(['controltowerai.io','www.controltowerai.io','weather.controltowerai.io'].includes(new URL(url).hostname)){chain.push({url,blocked:'Production host excluded'});break;}const r=await c.request.get(url,{maxRedirects:0,timeout:20000});chain.push({url,status:r.status()});if(r.status()>=300&&r.status()<400&&r.headers().location){url=new URL(r.headers().location,url).href;continue;}break;}}catch(e){chain.push({url,error:e.message.split('\n')[0]});}report.external.push({original,chain});}
for(const url of ['https://neomundi.cloud/wp-sitemap.xml','https://neomundi.cloud/wp-sitemap-posts-page-1.xml']){const r=await c.request.get(url,{maxRedirects:0});const body=await r.text();report.sitemaps.push({url,status:r.status(),containsRetiredURL:/<loc>[^<]*\/for-media\//.test(body)});assert(!report.sitemaps.at(-1).containsRetiredURL);}
}finally{fs.writeFileSync(path.join(out,'links.json'),JSON.stringify(report,null,2));await b.close();}console.log(JSON.stringify(report,null,2));})().catch(e=>{console.error(e);process.exitCode=1;});
